[build]
  # command = "npm run build"
  command = "npm run build && npm run opt"
  publish = ".next"

[[plugins]]
package = "/plugins/cache-images"

# [build.environment]
# NETLIFY_NEXT_PLUGIN_SKIP = "true"